## Importando bibliotecas

Fazer 4 aulas de Python e 3 de InglÃªs

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Leitura de arquivos

#### Netflix

In [28]:
df_netflix = pd.read_csv('/content/netflix_titles.csv')
df_netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [29]:
df_netflix.tail(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### Amazon

In [2]:
df_amazon = pd.read_csv('/content/amazon_prime_titles.csv')
df_amazon.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, BeyoncÃ©, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [3]:
df_amazon.tail(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

## Conhecendo nossos dados

#### Netflix

In [ ]:
df_netflix.shape

(8807, 12)

In [ ]:
df_netflix.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [ ]:
df_netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
df_netflix.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
df_netflix.duplicated().sum()

np.int64(0)

In [ ]:
df_netflix.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

In [ ]:
# categorias do type
df_netflix['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

**ObservaÃ§Ãµes:**
- Tratar as colunas nulas
- Verificar se Ã© relevante mudar o tipo de dados da coluna *date_added* e *duration*
- Renomear coluna *listed_in* para **gender** e verificar como separar esses dados
- Tratar dados ausentes de *director, cast, country, date_added, rating, duration*
- Filtrar os tipos de mÃ­dia

#### Amazon

In [4]:
df_amazon.shape

(9668, 12)

In [6]:
df_amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7585 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB

In [7]:
df_amazon.isnull().sum()

show_id            0
type               0
title              0
director        2083
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [8]:
# categorias do type
df_amazon['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

## Tratamento dos dados

### Netflix

In [30]:
df_netflix_tratando = df_netflix.copy()

In [31]:
df_netflix_tratando = df_netflix_tratando.rename(columns={'listed_in': 'gender'})

Novo dataframe sÃ³ com filmes e outro com TV Show

#### Movies

In [32]:
# filtrar os tipos de mÃ­dia
df_netflix_movies = df_netflix_tratando[df_netflix_tratando['type'] == 'Movie']

In [33]:
df_netflix_movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,gender,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, JosÃ© Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...

Na coluna *duration* do df 'df_netflix_movies' remover caracteres, deixando apenas nÃºmeros e depois transformar

In [34]:
df_netflix_movies['duration'] = df_netflix_movies['duration'].str.replace(' min', '')

/tmp/ipython-input-34-2512783283.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_movies['duration'] = df_netflix_movies['duration'].str.replace(' min', '')

In [35]:
# Observando os valores nulos
df_netflix_movies[df_netflix_movies['duration'].isnull()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,gender,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [36]:
# Transformar str em float
df_netflix_movies['duration']= df_netflix_movies['duration'].astype(float)

/tmp/ipython-input-36-1367438238.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_movies['duration']= df_netflix_movies['duration'].astype(float)

In [37]:
df_netflix_movies.describe()

       release_year     duration
count   6131.000000  6128.000000
mean    2013.121514    99.577187
std        9.678169    28.290593
min     1942.000000     3.000000
25%     2012.000000    87.000000
50%     2016.000000    98.000000
75%     2018.000000   114.000000
max     2021.000000   312.000000

In [38]:
df_netflix_movies['date_added'] = pd.to_datetime(df_netflix_movies['date_added'], errors='coerce')

/tmp/ipython-input-38-1311306791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_movies['date_added'] = pd.to_datetime(df_netflix_movies['date_added'], errors='coerce')

In [39]:
df_netflix_movies['date_added'] = df_netflix_movies['date_added'].dt.date

/tmp/ipython-input-39-4144583954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_movies['date_added'] = df_netflix_movies['date_added'].dt.date

In [40]:
df_netflix_movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6131 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6131 non-null   object
 1   type          6131 non-null   object
 2   title         6131 non-null   object
 3   director      5943 non-null   object
 4   cast          5656 non-null   object
 5   country       5691 non-null   object
 6   date_added    6131 non-null   object
 7   release_year  6131 non-null   int64
 8   rating        6129 non-null   object
 9   duration      6128 non-null   float64
 10  gender        6131 non-null   object
 11  description   6131 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 751.7+ KB

#### Investigando os valores nulos

In [ ]:
df_netflix_movies[df_netflix_movies['country'].isnull()]
# substituir 'country' pelo nome das outras variÃ¡veis vazias

#### TV Show

In [ ]:
df_netflix_series = df_netflix_tratando[df_netflix_tratando['type'] == 'TV Show']

In [ ]:
df_netflix_series.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2676 entries, 1 to 8803
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       2676 non-null   object
 1   type          2676 non-null   object
 2   title         2676 non-null   object
 3   director      230 non-null    object
 4   cast          2326 non-null   object
 5   country       2285 non-null   object
 6   date_added    2578 non-null   object
 7   release_year  2676 non-null   int64
 8   rating        2674 non-null   object
 9   duration      2676 non-null   object
 10  gender        2676 non-null   object
 11  description   2676 non-null   object
dtypes: int64(1), object(11)
memory usage: 271.8+ KB

In [ ]:
#df_netflix_series['date_added'] = pd.to_datetime(df_netflix_series['date_added'], errors='coerce') #first
df_netflix_series['date_added'] = df_netflix_series['date_added'].dt.date # second

/tmp/ipython-input-34-454691910.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_series['date_added'] = df_netflix_series['date_added'].dt.date # second

In [ ]:
# Fazer isso primeiro, depois transformar
#df_netflix_series['date_added'] = df_netflix_series['date_added'].str.strip(), format='%B %d, %Y' # removendo espaÃ§o em branco e transformando em data

In [ ]:
df_netflix_series['duration'] = df_netflix_series['duration'].str.replace(' Seasons', '')
df_netflix_series['duration'] = df_netflix_series['duration'].str.replace(' Season', '')

/tmp/ipython-input-38-999241174.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_series['duration'] = df_netflix_series['duration'].str.replace(' Seasons', '')
/tmp/ipython-input-38-999241174.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_series['duration'] = df_netflix_series['duration'].str.replace(' Season', '')

In [ ]:
# transformar coluna duration em float
df_netflix_series['duration'] = df_netflix_series['duration'].astype(float)

/tmp/ipython-input-39-2044770982.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_series['duration'] = df_netflix_series['duration'].astype(float)

In [ ]:
df_netflix_series.describe()

       release_year     duration
count   2676.000000  2676.000000
mean    2016.605755     1.764948
std        5.740138     1.582752
min     1925.000000     1.000000
25%     2016.000000     1.000000
50%     2018.000000     1.000000
75%     2020.000000     2.000000
max     2021.000000    17.000000

### Amazon

In [9]:
# Criando uma cÃ³pia
df_amazon_tratando = df_amazon.copy()

In [10]:
df_amazon_tratando = df_amazon_tratando.rename(columns={'listed_in': 'gender'})

#### Movies

In [13]:
df_amazon_movies = df_amazon_tratando[df_amazon_tratando['type'] == 'Movie']

In [26]:
df_amazon_movies.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,gender,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113.0,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110.0,"Drama, International",A Metro Family decides to fight a Cyber Crimin...

In [18]:
df_amazon_movies['duration'] = df_amazon_movies['duration'].str.replace(' min', '')

/tmp/ipython-input-18-4021080201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_amazon_movies['duration'] = df_amazon_movies['duration'].str.replace(' min', '')

In [25]:
df_amazon_movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7814 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7814 non-null   object
 1   type          7814 non-null   object
 2   title         7814 non-null   object
 3   director      7585 non-null   object
 4   cast          7050 non-null   object
 5   country       569 non-null    object
 6   date_added    16 non-null     object
 7   release_year  7814 non-null   int64
 8   rating        7483 non-null   object
 9   duration      7814 non-null   float64
 10  gender        7814 non-null   object
 11  description   7814 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 1.0+ MB

In [24]:
# Transformar str em float
df_amazon_movies['duration']= df_amazon_movies['duration'].astype(float)

/tmp/ipython-input-24-623612469.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_amazon_movies['duration']= df_amazon_movies['duration'].astype(float)

#### TV Show

In [14]:
df_amazon_series = df_amazon_tratando[df_amazon_tratando['type'] == 'TV Show']

## AnÃ¡lise Filmes - Movies from Netflix

In [ ]:
df_netflix_movies.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,gender,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90.0,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, JosÃ© Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,2021-09-24,2021,PG,91.0,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...

In [ ]:
df_director = df_netflix_movies.groupby('director')['title'].count().sort_values(ascending=False)
df_director

director
Rajiv Chilaka              19
RaÃºl Campos, Jan Suter     18
Suhas Kadav                16
Marcus Raboy               15
Jay Karas                  14
                           ..
Jude Okwudiafor Johnson     1
Jude Weng                   1
Julia Hart                  1
Julia Knowles               1
Juan Antin                  1
Name: title, Length: 4354, dtype: int64

In [ ]:
# Verificando os diretores que tem mais de um filme
df_director_filter = df_director[df_director > 1]
df_director_filter

director
Rajiv Chilaka             19
RaÃºl Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              15
Jay Karas                 14
                          ..
Alexis Morante             2
Angelina Jolie             2
A. L. Vijay                2
Chris Sivertson            2
Chris Robinson             2
Name: title, Length: 833, dtype: int64

In [ ]:
df_release_year = df_netflix_movies.groupby('release_year')['title'].count().sort_values(ascending=False)
df_release_year

release_year
2018    767
2017    767
2016    658
2019    633
2020    517
       ...
1946      1
1963      1
1961      1
1959      1
1966      1
Name: title, Length: 73, dtype: int64

In [ ]:
# Filtrando
df_release_year_filter = df_release_year[df_release_year > 11]
df_release_year_filter

release_year
2018    767
2017    767
2016    658
2019    633
2020    517
2015    398
2021    277
2014    264
2013    225
2012    173
2010    154
2011    145
2009    118
2008    113
2006     82
2007     74
2005     67
2004     55
2003     51
2002     44
2001     40
1997     34
2000     33
1999     32
1998     32
1993     24
1995     23
1996     21
1994     20
1992     20
1990     19
1982     17
1988     16
1991     16
1989     15
1984     12
1981     12
Name: title, dtype: int64

In [ ]:
# Agrupar quantidade de filmes por paÃ­s
df_movies_country = df_netflix_movies.groupby('country')['title'].count().sort_values(ascending=False)
df_movies_country

country
United States                                                                          2058
India                                                                                   893
United Kingdom                                                                          206
Canada                                                                                  122
Spain                                                                                    97
                                                                                       ...
Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong       1
Ireland, Canada, United Kingdom, United States                                            1
Ireland, Canada, Luxembourg, United States, United Kingdom, Philippines, India            1
Ireland, Canada                                                                           1
India, Iran                                                                               1
Name: title, Length: 651, dtype: int64

In [ ]:
df_movies_country_filter = df_movies_country[df_movies_country > 10]
df_movies_country_filter

country
United States                    2058
India                             893
United Kingdom                    206
Canada                            122
Spain                              97
Egypt                              92
Nigeria                            86
Indonesia                          77
Japan                              76
Turkey                             76
France                             75
Philippines                        73
Mexico                             70
United Kingdom, United States      63
United States, Canada              51
Hong Kong                          50
Brazil                             50
Germany                            47
South Korea                        41
Australia                          39
United States, United Kingdom      38
Argentina                          38
Thailand                           37
Italy                              32
Canada, United States              32
China                              28
South Africa                       24
France, Belgium                    24
Poland                             18
United States, Germany             17
Malaysia                           16
Hong Kong, China                   16
Netherlands                        15
United States, France              14
Pakistan                           14
Taiwan                             13
United Arab Emirates               13
China, Hong Kong                   13
Colombia                           13
Germany, United States             12
United States, Mexico              11
Chile                              11
Name: title, dtype: int64

In [ ]:
df_movies_country.head(10)

country
United States     2058
India              893
United Kingdom     206
Canada             122
Spain               97
Egypt               92
Nigeria             86
Indonesia           77
Japan               76
Turkey              76
Name: title, dtype: int64

In [ ]:
# salvando o dataset de filmes
df_netflix_movies.to_csv('netflix_movies.csv', index=False)

In [ ]:
# importar biblioteca para baixar automaticamente quando rodar o prÃ³ximo cÃ³digo
from google.colab import files
files.download('netflix_movies.csv')

## Agrupamento Filmes Amazon e Netflix

Criando colunas chave para agrupamento

In [43]:
# Netflix
df_netflix_movies['title_id'] = df_netflix_movies['title'].str.lower().str.replace(" ", "")

/tmp/ipython-input-43-3778486959.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_movies['title_id'] = df_netflix_movies['title'].str.lower().str.replace(" ", "")

In [44]:
df_netflix_movies.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,gender,description,title_id
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90.0,Documentaries,"As her father nears the end of his life, filmm...",dickjohnsonisdead
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, JosÃ© Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,2021-09-24,2021,PG,91.0,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,mylittlepony:anewgeneration

In [45]:
df_amazon_movies['title_id'] = df_amazon_movies['title'].str.lower().str.replace(" ", "")

/tmp/ipython-input-45-3355196872.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_amazon_movies['title_id'] = df_amazon_movies['title'].str.lower().str.replace(" ", "")

In [46]:
df_amazon_movies.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,gender,description,title_id
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113.0,"Comedy, Drama",A small fishing village must procure a local d...,thegrandseduction
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110.0,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,takecaregoodnight

In [47]:
# Filmes em comum
df_netflix_amazon_movies = pd.merge(df_netflix_movies, df_amazon_movies, on='title_id', how='inner')

In [48]:
df_netflix_amazon_movies

,show_id_x,type_x,title_x,director_x,cast_x,country_x,date_added_x,release_year_x,rating_x,duration_x,...,title_y,director_y,cast_y,country_y,date_added_y,release_year_y,rating_y,duration_y,gender_y,description_y
0,s30,Movie,Paranoia,Robert Luketic,"Liam Hemsworth, Gary Oldman, Amber Heard, Harr...","United States, India, France",2021-09-19,2013,PG-13,106.0,...,Paranoia,Robert Luketic,"Harrison Ford, Liam Hemsworth, Amber Heard, Ga...",NaN,NaN,2013,PG-13,106.0,"Drama, Suspense",An entry-level employee at a powerful corporat...
1,s47,Movie,Safe House,Daniel Espinosa,"Denzel Washington, Ryan Reynolds, Vera Farmiga...","South Africa, United States, Japan",2021-09-16,2012,R,115.0,...,Safe House,Jeff Glickman,"Andrew Chapman, Leo Choy, Alex Hook, Deanna Li...",NaN,NaN,2021,18+,95.0,"Comedy, Suspense","On the verge of being fired, an FBI analyst se..."
2,s113,Movie,Worth,Sara Colangelo,"Michael Keaton, Stanley Tucci, Amy Ryan, Shuno...",NaN,2021-09-03,2021,PG-13,119.0,...,Worth,Jenn Page,Eric Roberts,NaN,NaN,2021,13+,90.0,"Drama, Special Interest, Suspense",Johnny was a young seminary student who lost h...
3,s119,Movie,Gurgaon,Shanker Raman,"Akshay Oberoi, Pankaj Tripathi, Ragini Khanna,...",India,2021-09-02,2017,TV-14,106.0,...,Gurgaon,Shanker Raman,"Pankaj Tripathi, Ragini Khanna, Akshay Oberoi,...",NaN,NaN,2017,13+,102.0,"Drama, Suspense",Nikki is jealous that his father considers his...
4,s140,Movie,Do the Right Thing,Spike Lee,"Danny Aiello, Ossie Davis, Ruby Dee, Richard E...",United States,2021-09-01,1989,R,120.0,...,Do the Right Thing,Spike Lee,"Danny Aiello, Ossie Davis, Ruby Dee, Richard E...",NaN,NaN,1989,R,121.0,"Comedy, Drama",Director Spike Lee's seminal exploration of ra...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,s8666,Movie,Urvi,Pradeep Verma,"Sruthi Hariharan, Shraddha Srinath, Shweta Pan...",India,2018-01-15,2017,TV-MA,121.0,...,Urvi,B.S.Pradeep Varma,"Shruthi Hariharan, Shraddha Srinath, Achyuth K...",NaN,NaN,2017,18+,122.0,"Drama, Suspense",A wall separates three woman from reaching the...
274,s8668,Movie,USS Indianapolis: Men of Courage,Mario Van Peebles,"Nicolas Cage, Tom Sizemore, Thomas Jane, Matt ...",United States,2019-09-25,2016,R,130.0,...,USS Indianapolis: Men of Courage,Mario Van Peebles,"Nicolas Cage, Matt Lanter, Thomas Jane, Tom Si...",NaN,NaN,2016,R,131.0,"Action, Drama","Nicolas Cage, Tom Sizemore and Thomas Jane sta..."
275,s8723,Movie,What Lies Beneath,Robert Zemeckis,"Harrison Ford, Michelle Pfeiffer, Diana Scarwi...",United States,2020-01-01,2000,PG-13,130.0,...,What Lies Beneath,Menno Meyjes,"Monic Hendrickx, Fedja van HuÃªt, Daan Schuurma...",NaN,NaN,2016,13+,95.0,Suspense,"After many years abroad, a woman's homecoming ..."
276,s8755,Movie,Wolves,Bart Freundlich,"Michael Shannon, Carla Gugino, Taylor John Smi...",United States,2019-03-29,2016,R,109.0,...,Wolves,David Hayter,"Jason Momoa, Lucas Till, Stephen McHattie, Mer...",NaN,NaN,2014,R,90.0,"Action, Horror, Science Fiction",A high-school student wakes to find he is chan...
277,s8758,Movie,World Trade Center,Oliver Stone,"Nicolas Cage, Michael PeÃ±a, Maggie Gyllenhaal,...",United States,2019-11-20,2006,PG-13,129.0,...,World Trade Center,Oliver Stone,"Nicolas Cage, Maria Bello, Jay Hernandez, Jon ...",United States,NaN,2006,PG-13,129.0,"Drama, Suspense",Nicolas Cage stars in the unforgettable true s...

In [49]:
# Todos os filmes
# pd.concat trÃ¡s repetido
# df_movies_v0 = pd.concat([df_netflix_movies, df_amazon_movies])

df_movies = pd.merge(df_netflix_movies, df_amazon_movies, on='title_id', how='outer')

In [50]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13669 entries, 0 to 13668
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id_x       6133 non-null   object
 1   type_x          6133 non-null   object
 2   title_x         6133 non-null   object
 3   director_x      5945 non-null   object
 4   cast_x          5658 non-null   object
 5   country_x       5693 non-null   object
 6   date_added_x    6133 non-null   object
 7   release_year_x  6133 non-null   float64
 8   rating_x        6131 non-null   object
 9   duration_x      6130 non-null   float64
 10  gender_x        6133 non-null   object
 11  description_x   6133 non-null   object
 12  title_id        13669 non-null  object
 13  show_id_y       7814 non-null   object
 14  type_y          7814 non-null   object
 15  title_y         7814 non-null   object
 16  director_y      7585 non-null   object
 17  cast_y          7050 non-null   object
 18  country_y       569 non-null    object
 19  date_added_y    16 non-null     object
 20  release_year_y  7814 non-null   float64
 21  rating_y        7483 non-null   object
 22  duration_y      7814 non-null   float64
 23  gender_y        7814 non-null   object
 24  description_y   7814 non-null   object
dtypes: float64(4), object(21)
memory usage: 2.6+ MB

In [52]:
df_movies.head(4)

,show_id_x,type_x,title_x,director_x,cast_x,country_x,date_added_x,release_year_x,rating_x,duration_x,...,title_y,director_y,cast_y,country_y,date_added_y,release_year_y,rating_y,duration_y,gender_y,description_y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"""Mixed Up""",Nishi Chawla,"UDAY KRISHNA, BETHANY RISHELL, LUCY BOND, SANJ...",NaN,NaN,2020.0,16+,106.0,"Drama, Romance","""Mixed Up"" examines casual factors that make u..."
1,s2037,Movie,#Alive,Cho Il,"Yoo Ah-in, Park Shin-hye",South Korea,2020-09-08,2020.0,TV-MA,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s2305,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,2020-07-01,2019.0,TV-14,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s5973,Movie,#cats_the_mewvie,Michael Margolis,NaN,Canada,2020-02-05,2020.0,TV-14,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN